### ISSUE TITLE
commit author

### ISSUE THREAD

**Issue by bahamas10** [bu6hunt3r/using-emacs#1]
i'm showing up as the commit author for a bunch of your repos for the last couple of months... did you at any time install my dotfiles and are currently using a `.gitconfig` with my information saved in it?

I got an email for this repository specifically because GitGuardian has detected an API key commited here:

```
Hello @bu6hunt3r
--
GitGuardian detected an API key from Google in the following commit pushed on March 4th 2020, 08:28:21 UTC.
GitGuardian, or "GG", is a "Good Guy" bot scanning  in real time GitHub commits for sensitive                       information. Once you have pushed sensitive  information to GitHub, this information is public and should be                       considered compromised.
Accidents happened to the best of us and will continue to happen. Sign up to our service to be notified if this happens again. We got a free tier for individual developers!
```

**Comment by bu6hunt3r** [comment]
@bahamas10
-- 
I'm sorry. As already being suggested, it was my fault by using wrong entry in some gitconfig.
